[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_NEWS_API_KEY = "${VITE_NEWS_API_KEY}"
  VITE_NEWS_API_URL = "https://newsapi.org/v2"